'use strict'

module.exports = {
  testEnvironment: 'node',
  testMatch: [
    // Only run fixture level tests to avoid running "libraries" ones.
    '<rootDir>/test/fixtures/*/*.test.js',
  ],
  setupFilesAfterEnv: ['<rootDir>/test/setupTests.js'],

  // We don't want to jest to watch the files generated by the scripts.
  watchPathIgnorePatterns: [
    '<rootDir>\\/test\\/fixtures\\/.*\\/build\\/',
    '<rootDir>\\/test\\/fixtures\\/.*\\/node_modules\\/',
    '<rootDir>\\/test\\/fixtures\\/.*\\/coverage\\/',
  ],
}
